import express from "express";
import cors from "cors";
import { config } from "./config/env";
import { authMiddleware } from "./middlewares/authMiddleware";
import { auditLogMiddleware } from "./middlewares/auditLogMiddleware";
import { requestLoggerMiddleware } from "./middlewares/requestLoggerMiddleware";
import { errorHandlerMiddleware } from "./middlewares/errorHandlerMiddleware";
import vesselRoutes from "./routes/VesselRoutes";
import berthRoutes from "./routes/BerthRoutes";
import berthPlanRoutes from "./routes/BerthPlanRoutes";
import yardSlotRoutes from "./routes/YardSlotRoutes";
import workTaskRoutes from "./routes/WorkTaskRoutes";
import { berthPlanService } from "./services/BerthPlanService";

const app = express();
app.use(cors());
app.use(express.json());
app.use(requestLoggerMiddleware);
app.use(authMiddleware);
app.use(auditLogMiddleware);
app.get("/health", (_req, res) => res.json({ status: "ok", service: "port-yard" }));
app.use("/api/vessel", vesselRoutes);
app.use("/api/berth", berthRoutes);
app.use("/api/berth-plan", berthPlanRoutes);
app.use("/api/yard-slot", yardSlotRoutes);
app.use("/api/work-task", workTaskRoutes);
app.use(errorHandlerMiddleware);
// 启动即自动重算一遍泊位压港，让步方进入 CONFLICT 并记入操作日志。
berthPlanService.recalculateConflicts(0);
app.listen(config.port, () => console.log("port-yard backend listening on", config.port));
