export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BERTH_PLAN_NOT_FOUND: "BERTH_PLAN_NOT_FOUND",
  BERTH_PLAN_INVALID_TIME: "BERTH_PLAN_INVALID_TIME",
  BERTH_PLAN_CONFLICT_APPROVAL_BLOCKED: "BERTH_PLAN_CONFLICT_APPROVAL_BLOCKED",
  BERTH_PLAN_RESCHEDULE_LOCKED: "BERTH_PLAN_RESCHEDULE_LOCKED"
} as const;
